reproduce:
  seed_everything: 3 # Union[int, null]
  deterministic_flag: True # Must be true for fully deterministic behaviour (slows down training)
  benchmark: False # Should be set to false for fully deterministic behaviour. Could potentially speed up training.
training:
  precision: 32
  max_epochs: 10000
  max_steps: 150000
  learning_rate: 0.0002
  weight_decay: 0
  gradient_clip_val: 1.0
  limit_train_batches: 1.0
  lr_scheduler:
    use: True
    total_steps: ${..max_steps}
    pct_start: 0.005
    div_factor: 25 # init_lr = max_lr / div_factor
    final_div_factor: 50000 # final_lr = max_lr / final_div_factor (this is different from Pytorch' OneCycleLR param)
validation:
  limit_val_batches: 1.0
  val_check_interval: null # Optional[int]
  check_val_every_n_epoch: 1 # Optional[int]
batch_size:
  train: 8
  eval: 8
hardware:
  num_workers:
    train: 6
    eval: 2
  gpus: 0 # Either a single integer (e.g. 3) or a list of integers (e.g. [3,5,6])
  dist_backend: "nccl"
logging:
  ckpt_every_n_epochs: 1
  train:
    metrics:
      compute: false
      detection_metrics_every_n_steps: null # Optional[int] -> null: every train epoch, int: every N steps
    log_model_every_n_steps: 5000
    log_every_n_steps: 500
    high_dim:
      enable: True
      every_n_steps: 5000
      n_samples: 4
  validation:
    high_dim:
      enable: True
      every_n_epochs: 1
      n_samples: 8
wandb:
  #   How to use: 
  #   1) resume existing wandb run:                                 set artifact_name & wandb_runpath
  #   2) resume full training state in new wandb run:               set artifact_name
  #   3) resume only model weights of checkpoint in new wandb run:  set artifact_name & resume_only_weights=True
  #
  #   In addition: you can specify artifact_local_file to load the checkpoint from disk.
  #   This is for example required for resuming training with DDP.
  wandb_runpath: null  # WandB run path. E.g. USERNAME/PROJECTNAME/1grv5kg6
  artifact_name: null # Name of checkpoint/artifact. Required for resuming. E.g. USERNAME/PROJECTNAME/checkpoint-1grv5kg6-last:v15
  artifact_local_file: null # If specified, will use the provided local filepath instead of downloading it. Required if resuming with DDP.
  resume_only_weights: False
  name: null
  group_name: null # Specify group name of the run
  project_name: DEOE
