defaults:
  - general
  - dataset: gen4
  - model: rnndet
  - _self_

img_save_path: '/home/zht/python_project/RVT_CAOD_v9/save_img/'
checkpoint: '/home/zht/python_project/RVT_CAOD_v9/checkpoints/epoch=002-step=140000-val_AP=0.38.ckpt'
use_test_set: True
hardware:
  num_workers:
    eval: 4
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 2
training:
  precision: 16
