name: ???
path: ???
train:
  sampling: 'mixed' # ('random', 'stream', 'mixed')
  random:
    weighted_sampling: False
  mixed:
    w_stream: 1
    w_random: 1
eval:
  sampling: 'stream'
data_augmentation:
  random:
    prob_hflip: 0.5
    rotate:
      prob: 0
      min_angle_deg: 2
      max_angle_deg: 6
    zoom:
      prob: 0.8
      zoom_in:
        weight: 8
        factor:
          min: 1
          max: 1.5
      zoom_out:
        weight: 2
        factor:
          min: 1
          max: 1.2
  stream:
    prob_hflip: 0.5
    rotate:
      prob: 0
      min_angle_deg: 2
      max_angle_deg: 6
    zoom:
      prob: 0.5
      zoom_out:
        factor:
          min: 1
          max: 1.2