defaults:
  - base

name: gen4
path: /data/zht/GEN4/GEN4_process
ev_repr_name: 'stacked_histogram_dt=50_nbins=10'
sequence_length: 5
training_classes:
  0: 'pedestrians'
  2: 'cars'
  # 3: 'trucks'
  # 5: 'traffic signs'
  # 6: 'traffic lights'
testing_classes:
  0: 'pedestrians'
  1: 'two wheelers'
  2: 'cars'
  3: 'trucks'
  4: 'buses'
  # 5: 'traffic signs'
  # 6: 'traffic lights'
unseen_classes:
  1: 'two wheelers'
  3: 'trucks'
  4: 'buses'
  # 5: 'traffic signs'
  # 6: 'traffic lights'



#training_classes: training_classes are the categories which are used for training, 
#in the process of data loading, we only load the images containing those categories;

#testing_classes: the categories used for testing, including the seen classes and unseen 
#classes, you can treat them as all the categories.

#unseen_classes: the categories that have not appeared in training classes
resolution_hw: [720, 1280]
downsample_by_factor_2: True
only_load_end_labels: False